Add parquet as a writer / datasource type to reth-indexer
joshstevens19/reth-indexer pull request #39
Opened 2023-12-28 20:47 UTC by liangjh

Add ability to write to local parquet file(s) within the existing reth-indexer multi-datasource framework. 

Utilize polars dataframe construction and serialization to fast-write to parquet format.

Generalize some type and column name components written for GCP to be utilized in parquet writer (+ can be used in other writers / formats in future). 

Linked to issue: https://github.com/joshstevens19/reth-indexer/issues/38

2024-01-08 15:53 UTC, joshstevens19 commented on src/datasource.rs
> +            let merged_column_types: IndexMap<String, String> = common_column_type_map
you can most likely chain these into 1 let with `common_column_type_map`

2024-01-08 15:57 UTC, joshstevens19 requested changes
tiny tiny code changes but over nice PR

2024-01-08 15:57 UTC, joshstevens19 commented on src/datasource.rs
> +            let merged_column_types: IndexMap<String, String> = common_column_type_map
you can most likely chain these into 1 let with `common_column_type_map`

2024-01-08 15:57 UTC, joshstevens19 commented on src/parquet.rs
> +        match res {
can you use an If let Error( instead of match here?

2024-01-08 15:57 UTC, joshstevens19 commented on src/parquet.rs
> +    match res {
same as above

2024-01-08 15:57 UTC, joshstevens19 commented on src/parquet.rs
> +            return Err(ParquetClientError::ParquetOperationError(format!(
probs but this in a fn and share it as its pasted 3 times in here

2024-01-08 15:57 UTC, joshstevens19 commented on src/parquet.rs
> +            match res {
same as above

2024-01-08 15:57 UTC, joshstevens19 commented on src/parquet.rs
> +                    match res {
same as a bove

2024-01-08 15:57 UTC, joshstevens19 commented on src/parquet.rs
> +                match res {
same as above

2024-01-09 04:27 UTC, liangjh commented
thx for the feedback re: `if let Err(...` pattern.  updated, lmk what you think -

2024-01-11 19:48 UTC, joshstevens19 approved these changes

2024-01-11 19:48 UTC, merged